---
title: "README"
output: html_document
date: "2024-05-06"
---

# Impact of Internet Access on Successful Births in Kenyan Health Facilities

This project analyzes the impact of internet access on successful births in Kenyan health facilities using data from the Service Delivery Indicators (SDI) surveys. The analysis is conducted using Stata.

## Data

The analysis uses data from  2018 rounds of the Kenya SDI surveys. The raw data files are:

- `sdi_kenya_2018_module1_anonymized.dta`: 2018 survey data

These files should be stored in the `data` subdirectory.

## Requirements

- Stata version 16 or later
- The following Stata packages:
  - `iebaltab`
- `pdslasso`
- `ivlasso`
- `estout`

You can install these packages using the `ssc install` command in Stata.  

## Directory Structure

The project has the following directory structure:
  
  ├── Data/
  │   ├── Source/
  │   │   ├── sdi_kenya_2012_module1_anonymized.dta
│   │   └── sdi_kenya_2018_module1_anonymized.dta
│   ├── data/
  │   ├── do/
  │   ├── figures/
  │   └── outtex/
  └── README.md

- `Data/Source/`: Contains the raw data files.
- `Data/data/`: Contains the cleaned and processed data files.
- `Data/do/`: Contains the Stata do-files for data cleaning and analysis.
- `Data/figures/`: Contains the figures and plots generated by the analysis.
- `Data/outtex/`: Contains the LaTeX tables generated by the analysis.

## Usage

1. Clone or download this repository.
2. Open Stata and set the working directory to the project root using the `cd` command.
3. Open the `analysis.do` file in the `do` subdirectory.
4. Update the `projectroot` global macro in the do-file to match your project's root directory.
5. Run the do-file to reproduce the analysis.

The do-file will load the raw data, clean and process it, generate descriptive statistics, balance tables, and regression models, and save the results in the `outtex` and `figures` subdirectories.


## Notes

- The do-file uses relative file paths to ensure portability across different machines. 
- The analysis is conducted using Stata version 16. Earlier versions may not be compatible.
- The do-file assumes that the required Stata packages are already installed. If not, uncomment the relevant `ssc install` commands.
- The project uses a sample of health facilities with at least one birth in 2018. The sample size and findings may differ if a different sample is used.

## Author

Emilien Akotenou (eakotenou@ou.edu)

## License

This project is licensed under the MIT License - see the [LICENSE](LICENSE) file for details.
